client_id = "9e0bf26577909d0642a6fc4cf844d5bb"
name = "BrandLogo"
handle = "brandlogo"
application_url = "https://brand-logo.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://brand-logo.onrender.com/auth/callback",
  "https://brand-logo.onrender.com/api/auth/callback",
  "https://brand-logo.onrender.com/auth/exit-iframe"
]

# POSを使わないなら、このブロック削除
# [pos]
# embedded = false

